### ISSUE TITLE
Allow setting remote config url using env variable

### ISSUE THREAD

**Issue by MiniGod** [amio/now-go#11]
It would be great if I could deploy `now-go` directly from this repo and point to the config using an env variable.

Something like

```
now -e NOW_GO_CONFIG=http://example.com/config.json amio/now-go
now alias https://now-go-ab78a901.now.sh/ short.example.com
```

I'm already hosting my website on gh-pages, so I could easily update the config there without having to create a new repo only for the shorturl service.

**Comment by amio** [comment]
Good idea!
